"use client";

// What the provider hands the app: the day's state, counts derived from it, and every action. Rebuilt only on change.

import { useMemo } from "react";
import { onDay } from "@/lib/days";
import { spentOn } from "@/lib/day/intervals";
import { daySnapshot } from "@/lib/day/snapshot";
import { inDay, workToday } from "@/lib/day/work";

export function useValue(v) {
  const {
    blocks,
    tasks,
    day,
    journal,
    setJournal,
    history,
    sessions,
    rest,
    pause,
    focusLocked,
    profile,
    setProfile,
    restMinutes,
    setRestMinutes,
    checkInMinutes,
    setCheckInMinutes,
    todayStamp,
    plans,
    plansReady,
    hydrated,
    loadFailed,
    retry,
    userId,
    skippedToday,
    miloMood,
    start,
    startAndLead,
    pauseDay,
    resumeDay,
    setPauseNote,
    endDay,
    skipRest,
    newDay,
    unseen,
    markSeen,
    addBlock,
    editBlock,
    removeBlock,
    archiveBlock,
    restoreBlock,
    dropBlock,
    undropBlock,
    reorderBlocks,
    toggleFocusLock,
    addTask,
    removeTask,
    moveTask,
    setTaskDays,
    setTaskKind,
    setTaskMinutes,
    setTaskNote,
    reorderTasks,
    setTaskStatus,
    addStep,
    toggleStep,
    reorderSteps,
    removeStep,
    skipTask,
    setAsideAhead,
    dayThemes,
    setDayTheme,
    clearDayTheme,
    completeSetup,
  } = v;

  return useMemo(() => {
    const inPlay = blocks.filter((b) => !b.archived);
    const live = inPlay.filter((b) => !b.dropped);
    // today's blocks: something in them today, or already under way — an empty block stays out of the lineup
    const dayBlocks = live.filter((b) => inDay(b, tasks, skippedToday));
    const paused = pause !== null;

    // counts per block for today, derived and never stored, so the lineup always matches the board
    const countsFor = (blockId) => {
      const mine = workToday(tasks, blockId, skippedToday);
      return {
        todo: mine.filter((t) => t.status === "todo").length,
        doing: mine.filter((t) => t.status === "doing").length,
        done: mine.filter((t) => t.status === "done").length,
      };
    };

    const ongoingBlock = live.find((b) => b.status === "ongoing") ?? null;

    return {
      blocks: live,
      dayBlocks,
      archived: blocks.filter((b) => b.archived),
      droppedToday: inPlay.filter((b) => b.dropped),
      // every block in your order, set aside or not — the Day ahead walks through these
      lineup: inPlay,
      tasks,
      todayStamp,
      plans,
      canPlan: hydrated && !loadFailed && plansReady && userId != null,
      // the one test for "is this task part of today": its weekdays, minus today's plan
      isToday: (t) => onDay(t) && !skippedToday.has(t.id),
      skipTask,
      setAsideAhead,
      blockById: Object.fromEntries(blocks.map((b) => [b.id, b])),
      start,
      startAndLead,
      focusLocked,
      addBlock,
      editBlock,
      removeBlock,
      archiveBlock,
      restoreBlock,
      dropBlock,
      undropBlock,
      toggleFocusLock,
      reorderBlocks,
      reorderTasks,
      setTaskStatus,
      countsFor,
      addTask,
      removeTask,
      moveTask,
      setTaskDays,
      setTaskKind,
      setTaskMinutes,
      setTaskNote,
      addStep,
      toggleStep,
      reorderSteps,
      removeStep,
      day,
      journal,
      setJournal,
      history,
      sessions,
      // derived, never stored; the caller passes `now`, so a ticking component sets its own pace
      spentOnBlock: (id, now) => spentOn(sessions, (x) => x.blockId === id, now),
      spentOnTask: (id, now) => spentOn(sessions, (x) => x.taskId === id, now),
      spentToday: (now) => spentOn(sessions, () => true, now),
      // which task the clock is on right now, if any
      runningTaskId: sessions.find((x) => x.endedAt === null)?.taskId ?? null,
      // false until the first read settles; anything that could flash a wrong answer waits on it
      hydrated,
      loadFailed,
      retry,
      endDay,
      newDay,
      unseen,
      markSeen,
      rest,
      skipRest,
      paused,
      // the whole pause, so the screen you land on can say where you were and read back your note
      pause,
      setPauseNote,
      pauseDay,
      resumeDay,
      restMinutes,
      setRestMinutes,
      checkInMinutes,
      setCheckInMinutes,
      // for widgets and lock screens: one plain payload, with nothing that counts what isn't done
      snapshot: (now) => daySnapshot({ live: dayBlocks, blocks, tasks, sessions }, now),
      // only ever counts up: no target, no percentage, no gap
      summary: {
        done: tasks.filter((t) => t.status === "done").length,
        blocksDone: blocks.filter((b) => b.status === "done").length,
        minutes: tasks.filter((t) => t.status === "done").reduce((m, t) => m + (t.minutes ?? 0), 0),
        startedAt: day.startedAt,
      },
      miloMood: paused ? "sleepy" : miloMood,
      profile,
      setProfile,
      // a theme per weekday: { tue: { name, emoji } }
      dayThemes,
      setDayTheme,
      clearDayTheme,
      completeSetup,
      ongoing: ongoingBlock ? { ...ongoingBlock, ...countsFor(ongoingBlock.id) } : null,
    };
  }, [
    blocks,
    tasks,
    day,
    journal,
    setJournal,
    history,
    sessions,
    rest,
    pause,
    focusLocked,
    profile,
    setProfile,
    restMinutes,
    setRestMinutes,
    checkInMinutes,
    setCheckInMinutes,
    todayStamp,
    plans,
    plansReady,
    hydrated,
    loadFailed,
    retry,
    userId,
    skippedToday,
    miloMood,
    start,
    startAndLead,
    pauseDay,
    resumeDay,
    setPauseNote,
    endDay,
    skipRest,
    newDay,
    unseen,
    markSeen,
    addBlock,
    editBlock,
    removeBlock,
    archiveBlock,
    restoreBlock,
    dropBlock,
    undropBlock,
    reorderBlocks,
    toggleFocusLock,
    addTask,
    removeTask,
    moveTask,
    setTaskDays,
    setTaskKind,
    setTaskMinutes,
    setTaskNote,
    reorderTasks,
    setTaskStatus,
    addStep,
    toggleStep,
    reorderSteps,
    removeStep,
    skipTask,
    setAsideAhead,
    dayThemes,
    setDayTheme,
    clearDayTheme,
    completeSetup,
  ]);
}
